version: "3"

vars:
  PKG_MNGR: npm
  PKG_MNGR_SCRIPT: "{{.PKG_MNGR}} run"
includes:
  example.vanilla:
    taskfile: ./examples/vanilla/Taskfile.yml
    dir: ./examples/vanilla
  example.react:
    taskfile: ./examples/react/Taskfile.yml
    dir: ./examples/react
  example.vue:
    taskfile: ./examples/vue/Taskfile.yml
    dir: ./examples/vue
  example.svelte:
    taskfile: ./examples/svelte/Taskfile.yml
    dir: ./examples/svelte
tasks:
  default:
    - task: dev
  dev: "{{.PKG_MNGR_SCRIPT}} dev"
  build: "{{.PKG_MNGR_SCRIPT}} build"
  build.all:
    cmds:
      - task: vm.build
      - task: vm.build-types
      - task: build
  lint: "{{.PKG_MNGR_SCRIPT}} lint"
  lint.fix: "{{.PKG_MNGR_SCRIPT}} lint:fix"
  format: "{{.PKG_MNGR_SCRIPT}} format"
  format.fix: "{{.PKG_MNGR_SCRIPT}} format:fix"
  check-types: "{{.PKG_MNGR_SCRIPT}} check-types"
  test: "{{.PKG_MNGR_SCRIPT}} test"
  docs.build: "{{.PKG_MNGR_SCRIPT}} docs:build"
  docs.dev: "{{.PKG_MNGR_SCRIPT}} docs:dev"
  docs.preview: "{{.PKG_MNGR_SCRIPT}} docs:preview"
  docs.build-and-preview:
    cmds:
      - task: docs.build
      - task: docs.preview
  pack-tarball: "{{.PKG_MNGR}} pack"
  deps: "{{.PKG_MNGR}} ci"
  sandbox.build: "{{.PKG_MNGR_SCRIPT}} sandbox:build"
  sandbox.dev: "{{.PKG_MNGR_SCRIPT}} sandbox:dev"
  sandbox.preview: "{{.PKG_MNGR_SCRIPT}} sandbox:preview"
  sandbox.build-and-preview:
    cmds:
      - task: sandbox.build
      - task: sandbox.preview
  vm.build: "{{.PKG_MNGR_SCRIPT}} vm:build"
  vm.build-types: "{{.PKG_MNGR_SCRIPT}} vm:build-types"
  prepare-release:
    cmds:
      - task: lint
      - task: check-types
      - task: build.all
      - task: test
  release:
    cmds:
      - task: prepare-release
      - "{{.PKG_MNGR_SCRIPT}} release"
